### ISSUE TITLE
[Bug] Zenoh Pico runs out of memory on Arduino

### ISSUE THREAD

**Issue by p-avital** [eclipse-zenoh/zenoh-pico#261] opened 2023-10-12 15:26 UTC
### Describe the bug

Defragmentation buffer seems to allocate too much memory for the arduino, ideally it shouldn't allocate on its own.

### To reproduce

Local zenoh demo

### System info

Arduino board

**Comment by cguimaraes** [comment] 2023-10-24 22:42
@p-avital shall we close this issue.
Did you check if by enabling dynamic memory allocations, the issue is also witnessed?

**Closed** 2023-11-29 08:51 UTC
Labels: bug
